// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiggerAsp.Data;

namespace TiggerAsp.Data.Migrations
{
    [DbContext(typeof(PhotoDbContext))]
    [Migration("20200316155805_AddHRs68-81")]
    partial class AddHRs6881
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TiggerAsp.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommentMemberId")
                        .HasColumnType("int");

                    b.Property<int>("CommentPhotoId")
                        .HasColumnType("int");

                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PhotoId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentActual = "Grandma Stella always had great penmanship!",
                            CommentMemberId = 0,
                            CommentPhotoId = 9
                        });
                });

            modelBuilder.Entity("TiggerAsp.Models.Occasion", b =>
                {
                    b.Property<string>("OccasionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OccasionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccasionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OccasionId");

                    b.ToTable("Occasions");

                    b.HasData(
                        new
                        {
                            OccasionId = "EH",
                            OccasionDescription = "Photos of Elisha and his children.",
                            OccasionName = "Early Hendrix Photos"
                        },
                        new
                        {
                            OccasionId = "HR67",
                            OccasionDescription = "The very first Hendrix Reunion.",
                            OccasionName = "Hendrix Reunion, 1967"
                        },
                        new
                        {
                            OccasionId = "00",
                            OccasionDescription = "Photos Home",
                            OccasionName = "Home"
                        },
                        new
                        {
                            OccasionId = "HR68",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1968"
                        },
                        new
                        {
                            OccasionId = "HR76",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1976"
                        },
                        new
                        {
                            OccasionId = "HR77",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1977"
                        },
                        new
                        {
                            OccasionId = "HR78",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1978"
                        },
                        new
                        {
                            OccasionId = "HR81",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1981"
                        },
                        new
                        {
                            OccasionId = "HR82",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1982"
                        },
                        new
                        {
                            OccasionId = "HR84",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1984"
                        },
                        new
                        {
                            OccasionId = "HR85",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1985"
                        },
                        new
                        {
                            OccasionId = "HR86",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1986"
                        },
                        new
                        {
                            OccasionId = "HR87",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1987"
                        },
                        new
                        {
                            OccasionId = "HR88",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1988"
                        },
                        new
                        {
                            OccasionId = "HR89",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1989"
                        },
                        new
                        {
                            OccasionId = "HR90",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1990"
                        });
                });

            modelBuilder.Entity("TiggerAsp.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccasionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotoId");

                    b.HasIndex("OccasionId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            PhotoId = 1,
                            Description = "Elisha and Orpha (Hazlett) Hendrix Family. Taken in 1934 at their home in Davis City, Iowa. Left - back row, Bill, Chet, Ed. Middle, Ruby, Jessie and Elisha; Front, Oliver and Jim.",
                            FileName = "EH-001.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 2,
                            Description = "Bill, Ed, Chet and Elisha Hendrix. All three are sons of Elisha. Taken at their home in Davis City, IA in 1936",
                            FileName = "EH-002.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 3,
                            Description = "The first one on the left is Oliver. He is very young here!",
                            FileName = "EH-003.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 4,
                            Description = "Oliver on left, Chet, Jessie, Ed, Bill, Jim and Ruby (not in picture) are all children of Elisha and Orpha (Hazlett) Hendrix!, taken fall of 1944.",
                            FileName = "EH-004.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 5,
                            Description = "Oliver and Jim, sons of Elisha and Orpha (Hazlett) Hendrix. Taken in 1944 on Chet and Mildred (Baughman) Hendrix's farm at Leon, Iowa.",
                            FileName = "EH-005.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 6,
                            Description = " Elisha and Orpha (Hazlett) Hendrix's sons. Chet standing on top of hay, Ed on left and Oliver, putting up hay on Chet's farm at Leon, Iowa in 1943..",
                            FileName = "EH-006.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 7,
                            Description = "Elisha and Orpha (Hazlett) Hendrix's sons. Oliver and Bill (on tractor), stacking hay on a farm around Leon, Iowa in 1939.",
                            FileName = "EH-007.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 8,
                            Description = "Oliver.",
                            FileName = "EH-008.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 9,
                            Description = "Written by Stella (Wood) Hendrix.",
                            FileName = "HR67-000.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 10,
                            Description = "Elisha and Orpha (Hazlett) Hendrix Family. Taken in 1934 at their home in Davis City, Iowa. Left - back row, Bill, Chet, Ed. Middle, Ruby, Jessie and Elisha; Front, Oliver and Jim.",
                            FileName = "EH-001downsizedframed.jpg",
                            OccasionId = "00"
                        },
                        new
                        {
                            PhotoId = 11,
                            Description = "Back row Michael, Francis and Cleveland, middle row their mother Orphia (Davis) Deevers and Debora and in front Russell",
                            FileName = "HR67-001.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 12,
                            Description = "Brothers, Ed and Bill Hendrix",
                            FileName = "HR67-002.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 13,
                            Description = "Judy (Hendrix) Bertelson",
                            FileName = "HR67-003.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 14,
                            Description = "Jim Hendrix",
                            FileName = "HR67-004.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 15,
                            Description = "Larry Hendrix",
                            FileName = "HR67-005.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 16,
                            Description = "On the left, ?,Pat Hendrix, Diane Hendrix and Linda (Hendrix) Burson holding ?",
                            FileName = "HR67-006.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 17,
                            Description = "In back Janice (Mrs Ed) Hendrix, Mary Ann (Mrs Jim) Hendrix and?, And in front Tony Hendrix and Diane Hendrix",
                            FileName = "HR67-007.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 18,
                            Description = "Eddie (Hendrix) Stuart and Shirley Hendrix",
                            FileName = "HR67-008.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 19,
                            Description = "Janice (Hendrix) Bartholomew and Larry Hendrix, sister and brother.",
                            FileName = "HR67-009.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 20,
                            Description = "Kay (Hendrix) Reed and daughter Joy Reed",
                            FileName = "HR67-010.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 21,
                            Description = "no description",
                            FileName = "HR67-011.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 22,
                            Description = "written by Stella Wood Hendrix",
                            FileName = "HR68-001.jpg",
                            OccasionId = "HR68"
                        },
                        new
                        {
                            PhotoId = 23,
                            Description = "no description",
                            FileName = "HR68-002.jpg",
                            OccasionId = "HR68"
                        },
                        new
                        {
                            PhotoId = 24,
                            Description = "Eddie (Hendrix) Stuart, Gayle Hendrix, Joyce and daughter Debbie Hendrix",
                            FileName = "HR68-003.jpg",
                            OccasionId = "HR68"
                        },
                        new
                        {
                            PhotoId = 25,
                            Description = "On the front bench are Norman and Linda (Hendrix) Burson and children, Doug and Chari. Beside Linda is Marcella (Mrs Art) Wood. Back row ?, Janice (Mrs Ed) Hendrix and ?",
                            FileName = "HR68-004.jpg",
                            OccasionId = "HR68"
                        },
                        new
                        {
                            PhotoId = 26,
                            Description = "no description",
                            FileName = "HR68-005.jpg",
                            OccasionId = "HR68"
                        },
                        new
                        {
                            PhotoId = 27,
                            Description = "Elizabeth, Dianna and their parents, LaDonna and Floyd Green.",
                            FileName = "HR68-006.jpg",
                            OccasionId = "HR68"
                        },
                        new
                        {
                            PhotoId = 28,
                            Description = "Dick and Gayle Hendrix",
                            FileName = "HR68-007.jpg",
                            OccasionId = "HR68"
                        },
                        new
                        {
                            PhotoId = 29,
                            Description = "Janice (Ed Hendrix), Diane and her mother Mary Ann (Jim Hendrix)",
                            FileName = "HR68-008.jpg",
                            OccasionId = "HR68"
                        },
                        new
                        {
                            PhotoId = 30,
                            Description = "In back, left Janice (Mrs Ed) Hendrix, Joyce (Mrs Ron) Hendrix and Mary Ann (Mrs Jim) Hendrix. In front, man in white shirt ?, and Jim Hendrix. I think the guy in the white shirt is Art Wood, Stella (Wood), (Mrs Bill) Hendrix's brother.",
                            FileName = "HR68-009.jpg",
                            OccasionId = "HR68"
                        },
                        new
                        {
                            PhotoId = 31,
                            Description = "I think those are the Dreevers sons, maybe their Dad and Ed Hendrix.",
                            FileName = "HR68-010.jpg",
                            OccasionId = "HR68"
                        },
                        new
                        {
                            PhotoId = 32,
                            Description = "written by Stella (Wood) Hendrix",
                            FileName = "HR76-001.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 33,
                            Description = "Oliver Hendrix",
                            FileName = "HR76-002.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 34,
                            Description = "Larry Hendrix (I think...) and his dad, Bill.",
                            FileName = "HR76-003.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 35,
                            Description = "Tom Bertelson (Judy Hendrix) and Jack Reed (Kay Hendrix)",
                            FileName = "HR76-004.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 36,
                            Description = "no description",
                            FileName = "HR76-005.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 37,
                            Description = "no description",
                            FileName = "HR76-006.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 38,
                            Description = "no description",
                            FileName = "HR76-007.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 39,
                            Description = "Gary Hendrix",
                            FileName = "HR76-008.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 40,
                            Description = "no description",
                            FileName = "HR76-009.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 41,
                            Description = "no description",
                            FileName = "HR76-010.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 42,
                            Description = "no description",
                            FileName = "HR76-011.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 43,
                            Description = "Bill Hendrix",
                            FileName = "HR76-012.jpg",
                            OccasionId = "HR76"
                        },
                        new
                        {
                            PhotoId = 44,
                            Description = "captured from Stella (Wood) Hendrix's photo albumn",
                            FileName = "HR77-001.jpg",
                            OccasionId = "HR77"
                        },
                        new
                        {
                            PhotoId = 45,
                            Description = "no description",
                            FileName = "HR77-002.jpg",
                            OccasionId = "HR77"
                        },
                        new
                        {
                            PhotoId = 46,
                            Description = "Janice ( Hendrix) Bartholomew on right",
                            FileName = "HR77-003.jpg",
                            OccasionId = "HR77"
                        },
                        new
                        {
                            PhotoId = 47,
                            Description = "Shirley (Hendrix)Morton in background, Chet Hendrix and Pat (Hendrix) Lease",
                            FileName = "HR77-004.jpg",
                            OccasionId = "HR77"
                        },
                        new
                        {
                            PhotoId = 48,
                            Description = "Greg Hendrix, Michelle Hendrix, Chari Burson, Tony Hendrix and in front Brad Bartholomew",
                            FileName = "HR77-005.jpg",
                            OccasionId = "HR77"
                        },
                        new
                        {
                            PhotoId = 49,
                            Description = "Chari Burson on right",
                            FileName = "HR77-006.jpg",
                            OccasionId = "HR77"
                        },
                        new
                        {
                            PhotoId = 50,
                            Description = "Greg, Michelle, Chari, Tony and Brad",
                            FileName = "HR77-007.jpg",
                            OccasionId = "HR77"
                        },
                        new
                        {
                            PhotoId = 51,
                            Description = "written by Stella (Wood) Hendrix",
                            FileName = "HR78-001.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 52,
                            Description = "Ed and Janice's family",
                            FileName = "HR78-002.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 53,
                            Description = "no description",
                            FileName = "HR78-003.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 54,
                            Description = "Mike and his Dad, Larry Hendrix",
                            FileName = "HR78-004.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 55,
                            Description = "Ralph Bethards and his Step-Mother, Jessie (Hendrix) Bethards",
                            FileName = "HR78-005.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 56,
                            Description = "In front, Mildred (Mrs Chet) Hendrix, Janice (Hendrix) (Mrs Fred) James, Mike (Kellie) Hendrix, ?, and Donnie (Marla) Hendrix",
                            FileName = "HR78-006.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 57,
                            Description = "Larry and Reta Hendrix and brother Gary Hendrix",
                            FileName = "HR78-007.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 58,
                            Description = "Oliver Hendrix and Donnie Hendrix",
                            FileName = "HR78-008.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 59,
                            Description = "Betty (Mrs Oliver) Hendrix",
                            FileName = "HR78-009.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 60,
                            Description = "Mildred (Mrs Chet) Hendrix, not sure who the little boy is, and Betty (Mrs Oliver) Hendrix, sister-in-laws! Little boy could be Darin Donnie and Marla Hendrix's son?",
                            FileName = "HR78-010.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 61,
                            Description = "written by Stella (Wood) Hendrix",
                            FileName = "HR78-011.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 62,
                            Description = "Mike Hendrix on left",
                            FileName = "HR78-012.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 63,
                            Description = "Harold Hendrix",
                            FileName = "HR78-013.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 64,
                            Description = "no description",
                            FileName = "HR78-014.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 65,
                            Description = "Janice James Behind ?, Mildred (Mrs Chet) Hendrix, Janice (Mrs Ed) Hendrix, front Kay (Mrs Jack) Reed and ? (I just can't decide which one of the boys that is) Kay Reed Jim Stuart jr.",
                            FileName = "HR78-015.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 66,
                            Description = "Hendrix cousins, Harold and Donnie!",
                            FileName = "HR78-016.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 67,
                            Description = "Marla ( Mrs Donnie) Hendrix",
                            FileName = "HR78-017.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 68,
                            Description = "Kay Reed Pat HendrixLease Kay Hendrix Reed Jim Stuart Jr joyce Hendrix and I think the one on the left is Tom Bertelson Judy Hendrix Bertelsons son Janice James Kay, between Jim and Joyce is another lady, not sure who she is? Is that your Mom standing up? Then Tom on the right, Tom and Judy Bertelson's son! Thanks for your help! As you have time, will you check other pictures to see if I have them correct!",
                            FileName = "HR78-018.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 69,
                            Description = "Hendrix brothers, Ed on left (Janice) and Bill (Stella)",
                            FileName = "HR78-019.jpg",
                            OccasionId = "HR78"
                        },
                        new
                        {
                            PhotoId = 70,
                            Description = "Kathy and Dennis Hendrix, Kathy holding Tacy, Tonya and Dennis holding Troy",
                            FileName = "HR81-001.jpg",
                            OccasionId = "HR81"
                        },
                        new
                        {
                            PhotoId = 71,
                            Description = "These are four of the Hendrix brothers; Chet, Oliver, Ed and Bill. Their brother Jim could not be there.",
                            FileName = "HR81-002.jpg",
                            OccasionId = "HR81"
                        },
                        new
                        {
                            PhotoId = 72,
                            Description = "Mary (Mrs Harold) Hendrix with son David",
                            FileName = "HR81-003.jpg",
                            OccasionId = "HR81"
                        },
                        new
                        {
                            PhotoId = 73,
                            Description = "These are all Hendrix cousins! On the left of table are Donnie, Gary and Denny and right side are Harold and Dick!",
                            FileName = "HR81-004.jpg",
                            OccasionId = "HR81"
                        },
                        new
                        {
                            PhotoId = 74,
                            Description = "Larry Hendrix, then-wife Rita, and daughter Michelle, with Chet Hendrix",
                            FileName = "HR81-005.jpg",
                            OccasionId = "HR81"
                        },
                        new
                        {
                            PhotoId = 75,
                            Description = "no description",
                            FileName = "HR81-006.jpg",
                            OccasionId = "HR81"
                        },
                        new
                        {
                            PhotoId = 76,
                            Description = "Eddie (Hendrix) (Mrs Jim) Stuart and granddaughter Nicole Stuart",
                            FileName = "HR81-007.jpg",
                            OccasionId = "HR81"
                        },
                        new
                        {
                            PhotoId = 77,
                            Description = " Hendrix cousins, Gary Hendrix and Kay (Hendrix) (Mrs Jack) Reed!",
                            FileName = "HR81-008.jpg",
                            OccasionId = "HR81"
                        },
                        new
                        {
                            PhotoId = 78,
                            Description = "Pat (Hendrix) (Mrs Ron) Lease",
                            FileName = "HR81-009.jpg",
                            OccasionId = "HR81"
                        },
                        new
                        {
                            PhotoId = 79,
                            Description = "Shirley (Hendrix) and Bob Morton.",
                            FileName = "HR81-010.jpg",
                            OccasionId = "HR81"
                        },
                        new
                        {
                            PhotoId = 80,
                            Description = "no description",
                            FileName = "HR81-011.jpg",
                            OccasionId = "HR81"
                        },
                        new
                        {
                            PhotoId = 81,
                            Description = "Ed and Janice Hendrix family - Shirley, Kay, Eddie, Ed, Janice, Dick, Judy and Pat !",
                            FileName = "HR81-012.jpg",
                            OccasionId = "HR81"
                        });
                });

            modelBuilder.Entity("TiggerAsp.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TiggerAsp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TiggerAsp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiggerAsp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TiggerAsp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TiggerAsp.Models.Comment", b =>
                {
                    b.HasOne("TiggerAsp.Models.User", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("TiggerAsp.Models.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");
                });

            modelBuilder.Entity("TiggerAsp.Models.Photo", b =>
                {
                    b.HasOne("TiggerAsp.Models.Occasion", "Occasion")
                        .WithMany()
                        .HasForeignKey("OccasionId");
                });
#pragma warning restore 612, 618
        }
    }
}
