// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiggerAsp.Data;

namespace TiggerAsp.Data.Migrations
{
    [DbContext(typeof(PhotoDbContext))]
    [Migration("20200316152856_AddHR67")]
    partial class AddHR67
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TiggerAsp.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommentMemberId")
                        .HasColumnType("int");

                    b.Property<int>("CommentPhotoId")
                        .HasColumnType("int");

                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PhotoId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentActual = "Grandma Stella always had great penmanship!",
                            CommentMemberId = 0,
                            CommentPhotoId = 9
                        });
                });

            modelBuilder.Entity("TiggerAsp.Models.Occasion", b =>
                {
                    b.Property<string>("OccasionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OccasionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccasionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OccasionId");

                    b.ToTable("Occasions");

                    b.HasData(
                        new
                        {
                            OccasionId = "EH",
                            OccasionDescription = "Photos of Elisha and his children.",
                            OccasionName = "Early Hendrix Photos"
                        },
                        new
                        {
                            OccasionId = "HR67",
                            OccasionDescription = "The very first Hendrix Reunion.",
                            OccasionName = "Hendrix Reunion, 1967"
                        },
                        new
                        {
                            OccasionId = "00",
                            OccasionDescription = "Photos Home",
                            OccasionName = "Home"
                        },
                        new
                        {
                            OccasionId = "HR68",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1968"
                        },
                        new
                        {
                            OccasionId = "HR76",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1976"
                        },
                        new
                        {
                            OccasionId = "HR77",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1977"
                        },
                        new
                        {
                            OccasionId = "HR78",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1978"
                        },
                        new
                        {
                            OccasionId = "HR81",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1981"
                        },
                        new
                        {
                            OccasionId = "HR82",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1982"
                        },
                        new
                        {
                            OccasionId = "HR84",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1984"
                        },
                        new
                        {
                            OccasionId = "HR85",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1985"
                        },
                        new
                        {
                            OccasionId = "HR86",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1986"
                        },
                        new
                        {
                            OccasionId = "HR87",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1987"
                        },
                        new
                        {
                            OccasionId = "HR88",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1988"
                        },
                        new
                        {
                            OccasionId = "HR89",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1989"
                        },
                        new
                        {
                            OccasionId = "HR90",
                            OccasionDescription = "",
                            OccasionName = "Hendrix Reunion, 1990"
                        });
                });

            modelBuilder.Entity("TiggerAsp.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccasionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotoId");

                    b.HasIndex("OccasionId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            PhotoId = 1,
                            Description = "Elisha and Orpha (Hazlett) Hendrix Family. Taken in 1934 at their home in Davis City, Iowa. Left - back row, Bill, Chet, Ed. Middle, Ruby, Jessie and Elisha; Front, Oliver and Jim.",
                            FileName = "EH-001.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 2,
                            Description = "Bill, Ed, Chet and Elisha Hendrix. All three are sons of Elisha. Taken at their home in Davis City, IA in 1936",
                            FileName = "EH-002.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 3,
                            Description = "The first one on the left is Oliver. He is very young here!",
                            FileName = "EH-003.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 4,
                            Description = "Oliver on left, Chet, Jessie, Ed, Bill, Jim and Ruby (not in picture) are all children of Elisha and Orpha (Hazlett) Hendrix!, taken fall of 1944.",
                            FileName = "EH-004.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 5,
                            Description = "Oliver and Jim, sons of Elisha and Orpha (Hazlett) Hendrix. Taken in 1944 on Chet and Mildred (Baughman) Hendrix's farm at Leon, Iowa.",
                            FileName = "EH-005.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 6,
                            Description = " Elisha and Orpha (Hazlett) Hendrix's sons. Chet standing on top of hay, Ed on left and Oliver, putting up hay on Chet's farm at Leon, Iowa in 1943..",
                            FileName = "EH-006.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 7,
                            Description = "Elisha and Orpha (Hazlett) Hendrix's sons. Oliver and Bill (on tractor), stacking hay on a farm around Leon, Iowa in 1939.",
                            FileName = "EH-007.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 8,
                            Description = "Oliver.",
                            FileName = "EH-008.jpg",
                            OccasionId = "EH"
                        },
                        new
                        {
                            PhotoId = 9,
                            Description = "Written by Stella (Wood) Hendrix.",
                            FileName = "HR67-000.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 10,
                            Description = "Elisha and Orpha (Hazlett) Hendrix Family. Taken in 1934 at their home in Davis City, Iowa. Left - back row, Bill, Chet, Ed. Middle, Ruby, Jessie and Elisha; Front, Oliver and Jim.",
                            FileName = "EH-001downsizedframed.jpg",
                            OccasionId = "00"
                        },
                        new
                        {
                            PhotoId = 11,
                            Description = "Back row Michael, Francis and Cleveland, middle row their mother Orphia (Davis) Deevers and Debora and in front Russell",
                            FileName = "HR67-001.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 12,
                            Description = "Brothers, Ed and Bill Hendrix",
                            FileName = "HR67-002.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 13,
                            Description = "Judy (Hendrix) Bertelson",
                            FileName = "HR67-003.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 14,
                            Description = "Jim Hendrix",
                            FileName = "HR67-004.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 15,
                            Description = "Larry Hendrix",
                            FileName = "HR67-005.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 16,
                            Description = "On the left, ?,Pat Hendrix, Diane Hendrix and Linda (Hendrix) Burson holding ?",
                            FileName = "HR67-006.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 17,
                            Description = "In back Janice (Mrs Ed) Hendrix, Mary Ann (Mrs Jim) Hendrix and?, And in front Tony Hendrix and Diane Hendrix",
                            FileName = "HR67-007.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 18,
                            Description = "Eddie (Hendrix) Stuart and Shirley Hendrix",
                            FileName = "HR67-008.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 19,
                            Description = "Janice (Hendrix) Bartholomew and Larry Hendrix, sister and brother.",
                            FileName = "HR67-009.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 20,
                            Description = "Kay (Hendrix) Reed and daughter Joy Reed",
                            FileName = "HR67-010.jpg",
                            OccasionId = "HR67"
                        },
                        new
                        {
                            PhotoId = 21,
                            Description = "no description",
                            FileName = "HR67-011.jpg",
                            OccasionId = "HR67"
                        });
                });

            modelBuilder.Entity("TiggerAsp.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TiggerAsp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TiggerAsp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiggerAsp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TiggerAsp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TiggerAsp.Models.Comment", b =>
                {
                    b.HasOne("TiggerAsp.Models.User", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("TiggerAsp.Models.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");
                });

            modelBuilder.Entity("TiggerAsp.Models.Photo", b =>
                {
                    b.HasOne("TiggerAsp.Models.Occasion", "Occasion")
                        .WithMany()
                        .HasForeignKey("OccasionId");
                });
#pragma warning restore 612, 618
        }
    }
}
